name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.82
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Run regression test
      run: ./target/debug/sus_compiler test.sus platform/xilinx/xpm.sus --ci --nocolor 1> test.sus_output_ci.txt 2> test.sus_errors_ci.txt || true && diff test.sus_output_ci.txt test.sus_output.txt && diff test.sus_errors_ci.txt test.sus_errors.txt
      
  lint:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.82
        override: true
        components: rustfmt, clippy
    - name: format
      run: cargo fmt --check
    - name: clippy
      run: RUSTFLAGS="-A unused" cargo clippy -- -Dwarnings
